name: cameraview360
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/subhasishpinku/cameraview360
repository: https://github.com/subhasishpinku/cameraview360

topics:
  - camera
  - panorama
  
environment:
  sdk: ^3.9.0-100.2.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera: ^0.10.5+5
  dchs_motion_sensors: ^2.0.1
  wakelock_plus: ^1.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.0
  flutter_image_compress: ^2.2.0
  vector_math: ^2.1.4
  shared_preferences: ^2.2.2
  ffi: ^2.0.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
